/*
 * Copyright 2026 Duatic AG
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following
 * disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 * following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
 * products derived from this software without  hardware_interface::CallbackReturn activate();t specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// NOTE: This header is autogenerated by the ros2 pkg tool during creating
// The license header was added to please pre-commit

#ifndef DUATIC_DUADRIVE_INTERFACE__VISIBILITY_CONTROL_H_
#define DUATIC_DUADRIVE_INTERFACE__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define DUATIC_DUADRIVE_INTERFACE_EXPORT __attribute__((dllexport))
#define DUATIC_DUADRIVE_INTERFACE_IMPORT __attribute__((dllimport))
#else
#define DUATIC_DUADRIVE_INTERFACE_EXPORT __declspec(dllexport)
#define DUATIC_DUADRIVE_INTERFACE_IMPORT __declspec(dllimport)
#endif
#ifdef DUATIC_DUADRIVE_INTERFACE_BUILDING_LIBRARY
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC DUATIC_DUADRIVE_INTERFACE_EXPORT
#else
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC DUATIC_DUADRIVE_INTERFACE_IMPORT
#endif
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC_TYPE DUATIC_DUADRIVE_INTERFACE_PUBLIC
#define DUATIC_DUADRIVE_INTERFACE_LOCAL
#else
#define DUATIC_DUADRIVE_INTERFACE_EXPORT __attribute__((visibility("default")))
#define DUATIC_DUADRIVE_INTERFACE_IMPORT
#if __GNUC__ >= 4
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC __attribute__((visibility("default")))
#define DUATIC_DUADRIVE_INTERFACE_LOCAL __attribute__((visibility("hidden")))
#else
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC
#define DUATIC_DUADRIVE_INTERFACE_LOCAL
#endif
#define DUATIC_DUADRIVE_INTERFACE_PUBLIC_TYPE
#endif

#endif  // DUATIC_DUADRIVE_INTERFACE__VISIBILITY_CONTROL_H_
